In [ ]:
# 数据收集的标准

# 1.数据下载
# 我一般从米筐下载数据（以下代码只能在米筐网站上用）
start_date = '2010-01-01'
end_date = '2022-01-01'
stocks = index_components('000300.XSHG', date=start_date)

def get_clean_price(stocks, start_date=None, end_date=None, fields='close'):
    # 获取指定日期范围内的价格数据
    price = get_price(stocks, start_date=start_date, end_date=end_date, fields=fields)
    
    # 重置索引并进行数据透视
    price = price.reset_index()
    price = price.pivot(index='date', columns='order_book_id', values=fields)
    
    return price

# 这个函数能够让你获得清理后的price数据（适用于alphalens结构）
price = get_clean_price(stocks, start_date, end_date, fields='close')

# 这个函数能够获取股票的fundamentals数据
fundamentals = get_price(stocks, start_date, end_date, frequency='1d', fields=None, adjust_type='pre', skip_suspended=False,expect_df=True)

# 这个函数可以用来获取财务数据（因子）
factors = [
    'market_cap',
    'revenue'
    'basic_earnings_per_share',
]
factor = get_factor(stocks, factors, start_date, end_date, universe=None, expect_df=True)

In [4]:
import pandas as pd
price = pd.read_hdf('/Users/syesw/Desktop/single_factor_research/data/hs300/hs300-20100101-20220101_price.h5', key='data')
price

order_book_id,000001.XSHE,000002.XSHE,000009.XSHE,000012.XSHE,000021.XSHE,000024.XSHE,000027.XSHE,000031.XSHE,000039.XSHE,000046.XSHE,...,601872.XSHG,601898.XSHG,601899.XSHG,601918.XSHG,601919.XSHG,601939.XSHG,601958.XSHG,601988.XSHG,601991.XSHG,601998.XSHG
date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,7.2969,6.4640,4.6810,5.9280,7.6948,16.0009,4.6634,9.9592,5.3788,5.6604,...,3.5720,10.2336,4.7198,11.3000,7.2399,2.9058,15.1265,1.9673,6.6924,4.5115
2010-01-05,7.1707,6.3177,4.5601,5.8273,7.8710,15.2800,4.6600,9.7503,5.4528,5.4641,...,3.6296,10.6214,4.8180,11.7370,7.4300,2.9485,15.7055,1.9902,6.8567,4.5674
2010-01-06,7.0476,6.3177,4.5557,6.0075,7.8182,15.3795,4.6530,9.7685,5.5514,5.4682,...,3.6871,10.7202,4.7493,11.6990,7.4458,2.9010,15.6412,1.9673,6.8343,4.4388
2010-01-07,6.9706,6.2689,4.6421,5.6898,7.9180,15.3484,4.5487,9.8956,5.4651,5.3946,...,3.5976,10.4313,4.6659,11.2937,7.2240,2.8583,15.5125,1.9306,6.6774,4.2879
2010-01-08,6.9553,6.3116,4.8666,5.6287,7.9063,15.5970,4.6008,9.9773,5.4733,5.4396,...,3.6296,10.4997,4.6266,11.0910,7.1923,2.8678,15.1828,1.9398,6.6401,4.3270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-27,16.5085,17.5668,13.8251,8.8987,15.5371,NaN,8.0435,3.6800,10.3690,1.9200,...,3.8913,6.1054,9.2355,4.6047,12.9815,5.1826,6.5506,2.6849,3.3551,4.0644
2021-12-28,16.4605,17.6205,14.1732,8.8797,15.7429,NaN,7.7769,3.7000,10.3011,1.8800,...,3.8913,5.9025,9.3608,4.4220,13.6063,5.2180,6.5795,2.6937,3.2166,4.0910
2021-12-29,16.0579,17.3519,14.1931,9.2881,15.4979,NaN,7.6722,3.6400,10.3258,1.8900,...,3.8722,5.8749,9.2740,4.4797,13.5022,5.1826,6.5699,2.6761,3.1176,4.0999
2021-12-30,16.1250,17.1191,14.1036,9.2406,15.5273,NaN,7.6817,3.6800,10.3134,1.8800,...,3.8817,5.8657,9.2933,4.4220,12.9815,5.1826,6.5699,2.6761,3.1671,4.0821
2021-12-31,15.7991,17.6921,14.3522,9.4305,15.5273,NaN,7.7103,3.7300,10.6039,1.8800,...,3.9008,5.8011,9.3512,4.3644,12.9746,5.1738,6.5988,2.6761,3.2067,4.0910

In [5]:
fundamentals = pd.read_hdf('/Users/syesw/Desktop/single_factor_research/data/hs300/hs300-20100101-20220101_fundamentals.h5', key='data')
fundamentals

                          limit_down    high  num_trades  limit_up  \
order_book_id date
600282.XSHG   2010-01-04      3.3659  3.7835      5126.0    4.1152
              2010-01-05      3.3474  3.7344      6562.0    4.0968
              2010-01-06      3.3167  3.7651      6384.0    4.0538
              2010-01-07      3.3351  3.7221      6463.0    4.0722
              2010-01-08      3.2553  3.6177      7102.0    3.9801
...                              ...     ...         ...       ...
000069.XSHE   2021-12-27      6.0435  7.0753     39433.0    7.3800
              2021-12-28      6.2302  6.9279     33262.0    7.6060
              2021-12-29      6.2302  7.0164     30397.0    7.6060
              2021-12-30      6.2597  7.0753     26662.0    7.6551
              2021-12-31      6.3187  7.0557     28133.0    7.7141

                          prev_close  total_turnover     low      volume  \
order_book_id date
600282.XSHG   2010-01-04        6.09    5.413038e+07  3.7037   8885788.0
              2010-01-05        6.06    7.556341e+07  3.6300  12612927.0
              2010-01-06        6.00    8.121317e+07  3.6484  13374774.0
              2010-01-07        6.03    7.241410e+07  3.5931  12149599.0
              2010-01-08        5.89    6.540368e+07  3.5010  11299982.0
...                              ...             ...     ...         ...
000069.XSHE   2021-12-27        6.83    5.410875e+08  6.7216  76970723.0
              2021-12-28        7.04    3.457782e+08  6.7412  49792377.0
              2021-12-29        7.04    2.862590e+08  6.8100  40632272.0
              2021-12-30        7.08    4.045816e+08  6.8493  56976402.0
              2021-12-31        7.14    3.505580e+08  6.8788  49490034.0

                            open   close
order_book_id date
600282.XSHG   2010-01-04  3.7589  3.7221
              2010-01-05  3.7221  3.6852
              2010-01-06  3.6852  3.7037
              2010-01-07  3.6852  3.6177
              2010-01-08  3.5870  3.6115
...                          ...     ...
000069.XSHE   2021-12-27  6.7314  6.9181
              2021-12-28  6.8690  6.9181
              2021-12-29  6.8886  6.9574
              2021-12-30  6.9476  7.0164
              2021-12-31  6.9771  6.9181

[852874 rows x 10 columns]

In [8]:
fundamentals.index[0]

('600282.XSHG', Timestamp('2010-01-04 00:00:00'))

In [9]:
finance_factors = pd.read_hdf('/Users/syesw/Desktop/single_factor_research/data/hs300/hs300-20100101-20220101_factors.h5', key='data')
finance_factors

                            market_cap  revenuebasic_earnings_per_share
order_book_id date
600282.XSHG   2010-01-04  1.020989e+10                              NaN
              2010-01-05  1.010880e+10                              NaN
              2010-01-06  1.015934e+10                              NaN
              2010-01-07  9.923472e+09                              NaN
              2010-01-08  9.906624e+09                              NaN
...                                ...                              ...
000069.XSHE   2021-12-27  5.774063e+10                              NaN
              2021-12-28  5.774063e+10                              NaN
              2021-12-29  5.806870e+10                              NaN
              2021-12-30  5.856081e+10                              NaN
              2021-12-31  5.774063e+10                              NaN

[869266 rows x 2 columns]

In [ ]:
# 在研究前先做好这些数据的准备，这种数据结构也方便用来做因子分析

In [ ]:
# 从米筐下载数据到本地
data.to_hdf('hs300_all_price_compressed_data.h5', key='data', mode='w', complevel=9, complib='blosc')